

module AbsGrammar where

-- Haskell module generated by the BNF converter




newtype Ident = Ident String deriving (Eq, Ord, Show, Read)
data Exp
    = EApp Exp Exp
    | EIf Exp Exp Exp
    | ELet Ident Exp Exp
    | EWhere Exp [Decl]
    | ELambda Ident Exp
    | EAdd Exp Exp
    | ESub Exp Exp
    | EMul Exp Exp
    | EDiv Exp Exp
    | EInt Integer
    | EVar Ident
  deriving (Eq, Ord, Show, Read)

data TypeDecl = TDecl Ident [Ident]
  deriving (Eq, Ord, Show, Read)

data TypeRef = TRef Ident [TypeRef]
  deriving (Eq, Ord, Show, Read)

data Variant = Var Ident [TypeRef]
  deriving (Eq, Ord, Show, Read)

data Decl = DConst Ident [Ident] Exp | DData TypeDecl [Variant]
  deriving (Eq, Ord, Show, Read)

